# Created with Devicie using komac v2.15.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: DavidMoore.IPFilterUpdater
PackageVersion: 3.0.5
PackageLocale: en-US
Publisher: David Moore
PublisherUrl: https://github.com/DavidMoore/ipfilter
PublisherSupportUrl: https://github.com/DavidMoore/ipfilter/issues
Author: David Moore
PackageName: IPFilter
PackageUrl: https://www.ipfilter.app/
License: MIT
LicenseUrl: https://github.com/DavidMoore/ipfilter/blob/HEAD/LICENSE.txt
Copyright: Copyright (c) 2016 David Moore
CopyrightUrl: https://raw.githubusercontent.com/DavidMoore/ipfilter/master/LICENSE.txt
ShortDescription: The ipfilter.dat file helps protect your privacy and security when using Bit Torrent by blocking a list of potentially malicious peers. This utility downloads and installs a selected list for your Bit Torrent client.
Moniker: ipfilter
Tags:
- ipfilter
- privacy
- security
- torrent
ReleaseNotes: |-
  Download and run IPFilter.msi to install. If you wish to just download and run the self-contained executable, you can download IPFilter.exe
  What's Changed
  Fixed 🛠
  - Fixing options quirks by @DavidMoore in #98
    - Options window should always enable OK and Cancel buttons (#74)
    - Fixed issue with deleting scheduled task after it's been disabled in options (#97)
  Full Changelog: 3.0.4-beta...3.0.5-beta
ReleaseNotesUrl: https://github.com/DavidMoore/ipfilter/releases/tag/3.0.5-beta
ManifestType: defaultLocale
ManifestVersion: 1.12.0
